version: 2
updates:
  # Enable version updates for Python dependencies
  - package-ecosystem: "uv"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/New_York"
    groups:
      production-dependencies:
        dependency-type: "production"
      development-dependencies:
        dependency-type: "development"
    open-pull-requests-limit: 10
    assignees:
      - "{{ cookiecutter.project_owner_github_username }}"
    reviewers:
      - "{{ cookiecutter.project_owner_github_username }}"
    labels:
      - "dependencies"
      - "python"
    commit-message:
      prefix: "chore"
      include: "scope"
    allow:
      - dependency-type: "all"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "{{ cookiecutter.project_owner_github_username }}"
    reviewers:
      - "{{ cookiecutter.project_owner_github_username }}"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Enable version updates for Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    assignees:
      - "{{ cookiecutter.project_owner_github_username }}"
    reviewers:
      - "{{ cookiecutter.project_owner_github_username }}"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "build"
      include: "scope"