version: '3.8'

services:
  dev:
    build:
      context: ..
      dockerfile: Dockerfile
      target: builder
      args:
        PYTHON_VERSION: {{ cookiecutter.python_version }}
        DEV_MODE: "true"
    volumes:
      # Mount the entire project directory
      - ..:/workspace:cached
      # Cache directories for faster rebuilds
      - uv-cache:/root/.cache/uv
    environment:
      - DEV_MODE=true
      - PYTHONPATH=/workspace/src
      - UV_COMPILE_BYTECODE=1
      - UV_LINK_MODE=copy
    working_dir: /workspace
    # Overwrite the default command to keep container running
    command: sleep infinity
    # Network mode for easier debugging and service access
    network_mode: host
    # Add capabilities needed for debugging
    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

volumes:
  uv-cache: