---
name: "Security"

on:
  workflow_dispatch:

permissions:
  contents: read
  security-events: write

env:
  python_version: "3.13"

defaults:
  run:
    shell: 'bash --noprofile --norc -Eeuo pipefail {0}'

jobs:
  analyze:
    name: CodeQL
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
        with:
          persist-credentials: 'false'
      - name: Bootstrap repository
        uses: ./.github/actions/bootstrap
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          python-version: ${{ env.python_version }}
      - name: Set CodeQL Python path
        run: |
          echo "CODEQL_PYTHON=$(uv run which python)" | tee -a "${GITHUB_ENV}"
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          setup-python-dependencies: false
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
